### PR TITLE
Rebuild for gdal33

### LINKED ISSUE #206: rasterio compliance with GDAL 3.3.0 ?
Hi,
Currently rasterio is not compliant with GDAL 3.3.0 released few days ago.

```
conda search -c conda-forge rasterio=1.2.4=py39hbc9cc8e_3 --info
- libgdal >=3.2.2,<3.3.0a0
```
Do you expect to release a version compliant with latest version of GDAL in the coming days?
thanks

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #206

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Builds with `proj` 7.2.0 aren't solvable so that's presumably why the bot hasn't done this migration yet.

**Comment by ocefpaf** [comment]
> Builds with `proj` 7.2.0 aren't solvable so that's presumably why the bot hasn't done this migration yet.

We can drop those for now. It is not sustainable to keep the older version for long. I'll push a few commits to your branch.

**Comment by xylar** [comment]
@ocefpaf, it seems like we need to add the migrator for `proj` back and then rerender.  I can do that.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> @ocefpaf, it seems like we need to add the migrator for `proj` back and then rerender. I can do that.

Ah yes! Sorry I missed that.

**Comment by xylar** [comment]
Looks like things are working now so I've set it to automerge.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@snowman2, any suggeston on the windows error we're seeing?
```
================================== FAILURES ===================================
_______________________ test_decimated_no_use_overview ________________________

self = <module 'py.error'>, func = <built-in function rename>
args = ('C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_decimated_no_use_overv...ministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_decimated_no_use_overview0\\red.tif.ovr')
kwargs = {}, __tracebackhide__ = False, cls = <class 'py.error.EEXIST'>
value = FileExistsError(17, 'Cannot create a file when that file already exists')
tb = <traceback object at 0x000001E90D34B288>, errno = 17

    def checked_call(self, func, *args, **kwargs):
        """ call a function and raise an errno-exception if applicable. """
        __tracebackhide__ = True
        try:
>           return func(*args, **kwargs)
E           FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_decimated_no_use_overview0\\green.tif.ovr' -> 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_decimated_no_use_overview0\\red.tif.ovr'

..\_test_env\lib\site-packages\py\_error.py:66: FileExistsError

During handling of the above exception, another exception occurred:
```

**Comment by snowman2** [comment]
> @snowman2, any suggeston on the windows error we're seeing?

Windows seems like it wants the file deleted first and then replaced instead of overwritten. Is the file able to be deleted first on Windows?

**Comment by xylar** [comment]
> Windows seems like it wants the file deleted first and then replaced instead of overwritten. Is the file able to be deleted first on Windows?

Yes, that was my reading, too.  I can fix it with a patch here but it would need to be fixed properly upstream, I think.

**Comment by xylar** [comment]
I think I'm just going to add it to the many tests we skip.  I don't really have time to deal with this properly, I'm afraid.

**Pull request merged**
