### PR TITLE
Update dev

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akrherz** [comment]
One error was

> ERROR: Package 'rasterio' requires a different Python: 3.8.19 not in '>=3.9

another was

> ModuleNotFoundError: No module named 'aiohttp'

**Review by akrherz — APPROVED** [review]
Thank you @ocefpaf

**Comment by akrherz** [comment]
Okay, transient hypothesis timing test failure on `test_outer_boundless_pixel_fidelity` on OSX.  Ironically, I was just restarting main branch builds this morning here to work around that flapping test.

**Comment by akrherz** [comment]
I am happy to merge this as is and babysit CI to restart the job, if necessary

**Comment by ocefpaf** [comment]
> I am happy to merge this as is and babysit CI to restart the job, if necessary

Thanks! I'm clocking out for the day BTW.

**Comment by akrherz** [comment]
Second failure, will try "third time is a charm" before pushing an isolated skip test commit

**Pull request merged**
