### PR TITLE
Bump to 0.35.0.post1

### PR DESCRIPTION
**Pull request by ocefpaf**
Changes
=======

0.35.0.post1 (2016-05-04)
-------------------------
- Bug fix: added rasterfill.cpp to MANIFEST.in so it is included in source
  distributions no matter the build system's GDAL version (#690).

0.35.0 (2016-05-04)
-------------------
- Requirements: affine requirement upped to >=1.3.0 (#430).
- Bug fix: passing an empty JSON object to `crs.from_string()` raises CRSError
  instead of passing silently (#628, #642).
- Bug fix: GDAL errors are no longer written to stderr; we no longer undefine
  error handlers (#649, #658).
- Bug fix: the Rasterio library only configures a NullHandler, applications
  must configure their own handlers to see Rasterio's log messages (#649,
  #658).
- Bug fix: AWS credentials are only sought by Rasterio when s3:// URLs are
  passed to `rasterio.open()` (#650, #665).
- Bug fix: window comparison functions now raise a ValueError when windows do
  not intersect instead of returning an empty sequence (#651, #656, #662).
- Bug fix: upgrade from deprecated Numpy usage in `read()` by explicitly
  converting window offsets to ints (#678, #680).
- Refactoring: window comparison functions may now take a variable number of
  windows as positional arguments in addition to a sequence of windows.
- Refactoring: logging is much finer grained now because we've changed to the
  `logger = logging.getLogger(__name__)` pattern throughout Rasterio (#649,
  #658).
- Refactoring: replaced old `drivers()` implementation with a new `Env` class
  and more consistent usage of it through the library and command line
  interface (#665, #682).

### CODE REVIEW

**Comment by ocefpaf** [comment]
Windows `TARGET_ARCH=x86` is failing. Not sure why :confused:

**Comment by ceholden** [comment]
Thanks for the update - I had waited because the PyPi link for the new release wasn't available. Do you know how the `pypi.python.org/packages/source` type of permanent URL becomes available? I've had no luck finding an answer.

I'm puzzled about the fail on x86 Windows as well. Not sure if I'll be able to figure it down, but I can give it a try sometime tonight.

**Comment by ocefpaf** [comment]
> Thanks for the update - I had waited because the PyPi link for the new release wasn't available. Do you know how the `pypi.python.org/packages/source` type of permanent URL becomes available? I've had no luck finding an answer.

They should be `pypi.io/packages/source` now, but we prefer the GitHub URLs (closer to the source) when the tags are reliable.

> I'm puzzled about the fail on x86 Windows as well. Not sure if I'll be able to figure it down, but I can give it a try sometime tonight.

Thanks! I will try to see if I can get a Windows machine to help.

**Comment by ceholden** [comment]
Hello from Windows! Getting setup wasn't actually that bad -- except for the Visual Studio eating up some 12 GB of space! Just had to grab [Visual Studio Community Edition](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs), ensuring to [enable "Common Tools for Visual C++ 2015" when installing](http://stackoverflow.com/a/35243904), and [grab MS Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266).

I can confirm that both `0.35.0.post1` and the newly released `0.35.1` fail the tests on my machine (but `0.34.0` does not so I think my environment is OK). Looks like any calls to `rasterio.open`, whether it's to create a new file or to open an existing, cause Python to crash.

This is literally the first piece of software I've built on Windows so I'm using fairly crude means of debugging, but I think I've made some progress. Testing against data included by rasterio under `tests/data/` by activating the `_test` environment used:

1. `gdalinfo rgb1.tif` works
2. Within Python, `rasterio.open("rgb1.tif")` crashes Python
3.`rio info rgb1.tif` crashes Python, but spits out the message:
    * `ERROR:rasterio._gdal:CPLE_OpenFailed in b'Unable to open EPSG support file gcs.csv.\nTry setting the GDAL_DATA environment variable to point to the\ndirectory containing EPSG csv files.'`
4. Setting GDAL_DATA fixes rasterio! For example,
    * `set GDAL_DATA=C:\conda\test\envs\_test\Library\share\gdal`
    * `rio info rgb1.tif` -- works!

The `gdal-activate.bat` script is installed under `<env root>\etc\conda\activate.d` as normal, but according to [this comment in the GDAL feedstock test suite](https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/run_test.py#L8), the activate script is never sourced when in the `_test` environment. There seem to be numerous issues on the `conda-build` repo that deal with this question.

If I add GDAL_DATA to `os.environ` in the `run_test.py` same as in the GDAL feedstock, the x86 build works. No clue why the x64 build works without this change. I wonder if the build might actually work if GDAL_DATA were being set as it usually is set.

That's about all I have sanity for tonight -- any clues on how to proceed?

**Comment by ocefpaf** [comment]
@ceholden awesome Windows debugging skills! If the issue is only the `GDAL_DATA` variable I know how to fix that. Send a new commit here soon...

PS: I also have no clue to why all other platforms worked.

**Comment by ocefpaf** [comment]
@ceholden not sure the env var was the issue. The abrupt end indicates a seg-fault, so we don't have any useful message from AppVeyor to use.

```
===== testing package: rasterio-0.35.0.post1-np110py27_0 ===== 
import: u'rasterio'
running run_test.py
C:\conda\envs\_test\lib\site-packages\rasterio\__init__.py:195: UserWarning: Dataset uses default geotransform (Affine.identity). No transform will be written to the output by GDAL.
  s.start()
TESTS FAILED: rasterio-0.35.0.post1-np110py27_0
 ```

@sgillies do you have any ideal of what might be happening on Windows x86 here? (x64 is fine BTW)

**Comment by ceholden** [comment]
@ocefpaf I think you forgot to add the var to the environment as, `os.environ['GDAL_DATA'] = gdalData`.

I literally did the same exact thing the first time I tried the fix

**Comment by ocefpaf** [comment]
> @ocefpaf I think you forgot to add the var to the environment as, `os.environ['GDAL_DATA'] = gdalData`.

Yep. Thanks for fixing that!

**Pull request merged**
