### PR TITLE
Rebuild gdal35 + disable tests?

### LINKED ISSUE #244: fix gdal35 rebuild
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

#242 

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

### LINKED ISSUE #245: @conda-forge-admin, please rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by ngam**
Fixes #244 
Fixes #245 
Closes #242 
Closes #246 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
For easier review / discussion, here are the disabled tests failure logs:

test_search_debian_gdal_data
```
mock_debian = local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0')

    def test_search_debian_gdal_data(mock_debian):
        """Find GDAL data under Debian locations"""
        finder = GDALDataFinder()
>       assert finder.search_debian(str(mock_debian)) == str(mock_debian.join("share").join("gdal").join("{}".format(str(gdal_version))))
E       AssertionError: assert None == '/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share/gdal/3.5'
E        +  where None = <bound method GDALDataFinder.search_debian of <rasterio._env.GDALDataFinder object at 0x7fddca507e10>>('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0')
E        +    where <bound method GDALDataFinder.search_debian of <rasterio._env.GDALDataFinder object at 0x7fddca507e10>> = <rasterio._env.GDALDataFinder object at 0x7fddca507e10>.search_debian
E        +    and   '/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0' = str(local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0'))
E        +  and   '/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share/gdal/3.5' = str(local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share/gdal/3.5'))
E        +    where local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share/gdal/3.5') = <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share/gdal')>('3.5')
E        +      where <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share/gdal')> = local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share/gdal').join
E        +        where local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share/gdal') = <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share')>('gdal')
E        +          where <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share')> = local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share').join
E        +            where local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0/share') = <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0')>('share')
E        +              where <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0')> = local('/tmp/pytest-of-conda/pytest-0/test_search_debian_gdal_data0').join
E        +      and   '3.5' = <built-in method format of str object at 0x7fddcc3f6430>('3.5')
E        +        where <built-in method format of str object at 0x7fddcc3f6430> = '{}'.format
E        +        and   '3.5' = str(GDALVersion(major=3, minor=5))


```

test_search_gdal_data_debian
```
mock_debian = local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0')

    def test_search_gdal_data_debian(mock_debian):
        """Find GDAL data under Debian locations"""
        finder = GDALDataFinder()
>       assert finder.search(str(mock_debian)) == str(mock_debian.join("share").join("gdal").join("{}".format(str(gdal_version))))
E       AssertionError: assert None == '/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share/gdal/3.5'
E        +  where None = <bound method GDALDataFinder.search of <rasterio._env.GDALDataFinder object at 0x7fddc99ff710>>('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0')
E        +    where <bound method GDALDataFinder.search of <rasterio._env.GDALDataFinder object at 0x7fddc99ff710>> = <rasterio._env.GDALDataFinder object at 0x7fddc99ff710>.search
E        +    and   '/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0' = str(local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0'))
E        +  and   '/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share/gdal/3.5' = str(local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share/gdal/3.5'))
E        +    where local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share/gdal/3.5') = <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share/gdal')>('3.5')
E        +      where <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share/gdal')> = local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share/gdal').join
E        +        where local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share/gdal') = <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share')>('gdal')
E        +          where <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share')> = local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share').join
E        +            where local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0/share') = <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0')>('share')
E        +              where <bound method LocalPath.join of local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0')> = local('/tmp/pytest-of-conda/pytest-0/test_search_gdal_data_debian0').join
E        +      and   '3.5' = <built-in method format of str object at 0x7fddcc3f61f0>('3.5')
E        +        where <built-in method format of str object at 0x7fddcc3f61f0> = '{}'.format
E        +        and   '3.5' = str(GDALVersion(major=3, minor=5))


```

test_info_azure_unsigned
```
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fddc8e92e10>
runner = <click.testing.CliRunner object at 0x7fddc9455450>

    @requires_gdal32(reason="Unsigned Azure requests require GDAL ~= 3.2")
    @pytest.mark.network
    def test_info_azure_unsigned(monkeypatch, runner):
        """Unsigned access to public dataset works"""
        monkeypatch.setenv('AZURE_NO_SIGN_REQUEST', 'YES')
        monkeypatch.setenv('AZURE_STORAGE_ACCOUNT', 'naipblobs')
        result = runner.invoke(main_group, ['info', 'az://naip/v002/md/2017/md_100cm_2017/39077/m_3907744_ne_18_1_20170628.tif'])
>       assert result.exit_code == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = <Result RasterioIOError('HTTP response code: 409')>.exit_code

tests/test_rio_info.py:436: AssertionError

```

**Review by ocefpaf — APPROVED** [review]
If possible I'd love to get more eyes here but these tests do look like something we should skip.

**Comment by xylar** [comment]
@ngam, I don't feel like I have any relevant expertise to offer, but the changes you made are fine with me.

**Comment by ocefpaf** [comment]
Let's merge and give it a try then. Thanks @ngam!

**Comment by ngam** [comment]
Thank you, we will keep an eye on it to make sure everything is good. Thanks all for the great work 🤩

**Comment by xylar** [comment]
Thank you @ngam for the hard work on this!

**Pull request merged**
