### PR TITLE
depend on libgdal-core and not gdal for #303

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Maybe we should have depended on `libgdal-core` and not `gdal` per https://github.com/conda-forge/rasterio-feedstock/issues/303#issuecomment-2377722919

@conda-forge-admin please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
@weiji14 , what do you think about this?  I suppose we could patch the build 0 metadata, but eh, perhaps not worth the fuss?

**Comment by weiji14** [comment]
Is there an actual difference in size between `libgdal-core` and `gdal`? I'm looking at the logs (e.g. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1037847&view=logs&jobId=517fe804-fa30-5dc2-1413-330699242c05&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=0e16a5ac-b304-53af-3e1e-5cbc230c8d59 and https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1038399&view=logs&jobId=517fe804-fa30-5dc2-1413-330699242c05&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=0e16a5ac-b304-53af-3e1e-5cbc230c8d59), and it's hard to tell...

**Comment by theroggy** [comment]
> Is there an actual difference in size between `libgdal-core` and `gdal`?

I wouldn't expect a significant one. A few megabytes, because it is only this package that won't be installed due to the change:
https://anaconda.org/conda-forge/gdal/files

**Review by weiji14 — APPROVED** [review]
> > Is there an actual difference in size between `libgdal-core` and `gdal`?
> 
> I wouldn't expect a significant one. A few megabytes, because it is only the package containing the standard GDAL python bindings that won't be installed due to the change: https://anaconda.org/conda-forge/gdal/files

Ah ok, I see what you mean now. So installing `gdal` from conda-forge does add some extra stuff that isn't needed by `rasterio` (specifically, the [`import osgeo.ogr, osgeo.gdal`](https://github.com/conda-forge/gdal-feedstock/blob/be22293716b72a071b62aba04871dd5ced698787/recipe/meta.yaml#L647-L648) Python bindings). So yes, we should use `libgdal-core` here to keep things smaller and be consistent with previous 1.3.x releases. Sorry for missing this in #316!

> I suppose we could patch the build 0 metadata, but eh, perhaps not worth the fuss?

Ideally yes... but I think bumping to build 1 is fine also :see_no_evil:

**Pull request merged**
