### PR TITLE
rebuild for proj810

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

attempt to address #218

### CODE REVIEW

**Comment by akrherz** [comment]
Appears we can't depsolve a libgdal=3.3 version with proj=8.1.0, boggling

**Comment by akrherz** [comment]
Well then
```
$ conda create -n dev python=3.8 libgdal=3.3 proj=8.1.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                         

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libstdcxx-ng conflicts for:
python=3.8 -> libffi[version='>=3.2.1,<3.3.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.2.0']
python=3.8 -> libstdcxx-ng[version='>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0']

Package proj conflicts for:
libgdal=3.3 -> proj[version='>=8.0.0,<8.0.1.0a0|>=8.0.1,<8.0.2.0a0']
libgdal=3.3 -> geotiff[version='>=1.7.0,<1.7.1.0a0'] -> proj[version='>=6.2.1,<6.2.2.0a0|>=8.1.0,<8.1.1.0a0|>=7.2.0,<7.2.1.0a0|>=7.1.1,<7.1.2.0a0|>=7.1.0,<7.1.1.0a0|>=7.0.0,<7.0.1.0a0']
proj=8.1.0

Package openssl conflicts for:
libgdal=3.3 -> openssl[version='>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a']
python=3.8 -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a']
libgdal=3.3 -> postgresql -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a']
proj=8.1.0 -> libcurl[version='>=7.77.0,<8.0a0'] -> openssl[version='>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a']

Package libgcc-ng conflicts for:
python=3.8 -> libgcc-ng[version='>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0']
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=4.9|>=7.2.0']

Package ncurses conflicts for:
python=3.8 -> ncurses[version='>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
python=3.8 -> readline[version='>=7.0,<8.0a0'] -> ncurses[version='5.9.*|>=6.0,<7.0a0|6.0.*']

Package python conflicts for:
libgdal=3.3 -> postgresql -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|3.4.*']
python=3.8The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - feature:|@/linux-64::__glibc==2.28=0
  - libgdal=3.3 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - proj=8.1.0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.28
```

**Comment by akrherz** [comment]
No libgdal=3.3 for proj=8.1 ???

```
$ conda info libgdal=3.3 | grep proj | uniq
    proj >=8.0.1,<8.0.2.0a0
    proj >=8.0.0,<8.0.1.0a0
    proj >=8.0.1,<8.0.2.0a0
    proj >=8.0.0,<8.0.1.0a0
    proj >=8.0.1,<8.0.2.0a0
```

Boggling

**Comment by akrherz** [comment]
:eyes: conda-forge/gdal-feedstock#536

**Comment by akrherz** [comment]
@conda-forge-admin, restart ci

**Comment by akrherz** [comment]
My PR vs #221 also drops the `click<8` pin, which I don't think it necessary anymore?

**Comment by akrherz** [comment]
@xylar , Greeeeeeeeen!

**Comment by xylar** [comment]
Thanks for the hard work getting this through!

**Comment by akrherz** [comment]
> Thanks for the hard work getting this through!

Thanks to you too!  Now, I await the epic disappointment of not being able to update to proj8.1!  Fingers crossed.

**Pull request merged**
