### PR TITLE
bump build number

### PR DESCRIPTION
**Pull request by ocefpaf**
Test the Windows failures.

### CODE REVIEW

**Comment by snowman2** [comment]
I wonder if this is related? https://github.com/mapbox/rasterio/issues/1787

**Comment by ocefpaf** [comment]
> I wonder if this is related? [mapbox/rasterio#1787](https://github.com/mapbox/rasterio/issues/1787)

The errors I'm investigating here are Windows only. We can add your test case to this PR and investigate it during the build but I disagree with https://github.com/mapbox/rasterio/issues/1787#issuecomment-534654525, you got the right set of packages and it was built with `gdal 3`.

**Comment by snowman2** [comment]
I disagree with [mapbox/rasterio#1787 (comment)](https://github.com/mapbox/rasterio/issues/1787#issuecomment-534654525), you got the right set of packages and it was built with `gdal 3`.

Needs more investigation for sure.

**Comment by ocefpaf** [comment]
> Needs more investigation for sure.

Just did,

```
conda create --name TEST rasterio libgdal=3 proj4
```

to get `proj4 6.1.1` and `libgdal 3.0.1`, got:

```
libgdal                   3.0.1                hf47eb90_8    conda-forge
proj4                     6.1.1                hc80f0dc_1    conda-forge
```

and I was able to run

```python
>>> import rasterio
>>> from rasterio.crs import CRS
>>> 
>>> cc = CRS.from_epsg(6933)
>>> 
>>> import rasterio
>>> from rasterio.crs import CRS
>>> 
>>> with rasterio.Env():
...     cc = CRS.from_epsg(6933)
```

without `gcs.csv` :-/

**Comment by snowman2** [comment]
Same for me:
```
$ rio --version
1.0.28
$ rio --gdal-version
3.0.1
$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rasterio.crs import CRS
>>> cc = CRS.from_epsg(6933)
>>> cc
CRS.from_epsg(6933)
```

**Comment by snowman2** [comment]
Wonder if a recent rebuild of GDAL fixed it? I cannot reproduce the issue anymore.

**Comment by ocefpaf** [comment]
> Wonder if a recent rebuild of GDAL fixed it? I cannot reproduce the issue anymore.

Could be. Or even a `conda` update and how it handles the env variable.

**Comment by snowman2** [comment]
> Could be. Or even a `conda` update and how it handles the env variable.

Maybe. But the env var was fine on the version with the issue.

**Comment by ocefpaf** [comment]
> > Could be. Or even a `conda` update and how it handles the env variable.
> 
> Maybe. But the env var was fine on the version with the issue.

Indeed. But the `gdal` build is also the same in my test.

**Pull request merged**
