### PR TITLE
Bump build no to catch up to latest GDAL

### PR DESCRIPTION
**Pull request by hobu**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hobu** [comment]
@conda-forge-admin please rerender

**Comment by xylar** [comment]
@hobu, I'm hoping you have a secret touch that I was lacking in #171 and #172

**Comment by hobu** [comment]
> @hobu, I'm hoping you have a secret touch that I was lacking in #171 and #172

Nope, I just neglected to search for any previous attempts 😄

**Comment by xylar** [comment]
Note, GDAL is being pegged via:
https://github.com/conda-forge/rasterio-feedstock/blob/master/recipe/conda_build_config.yaml#L1-L3
so unless you remove that, a rerender won't take care of this.

I found that tests failed with the latest GDAL and we're hoping (based on little evidence) that the latest proj (7.1.1) might work but that migration is currently stuck on GDAL's windows build: https://github.com/conda-forge/gdal-feedstock/pull/411, as is an attempt to update to the latest GDAL version: https://github.com/conda-forge/gdal-feedstock/pull/410

Long story sort, I think we're not yet at a point where `rasterio` is ready to be updated to the latest gdal/proj.

**Comment by hobu** [comment]
Thanks for the background. That GDAL error looks like something must have changed in the windows include path resolution or definition for the Python extensions. 

It would be better for everyone if we just moved those bindings out of GDAL's tree entirely and managed them like normal Python extensions are managed nowadays.

**Pull request closed without merging**
