### PR TITLE
Test main branch rebuild with no changes

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Would like to see if main branch even builds without any changes.

### CODE REVIEW

**Comment by akrherz** [comment]
previous working main branch build appeared to be gdal 3.6.0 and proj 9.1.0

**Comment by akrherz** [comment]
Good, same failures as in #262, pinning down gdal to 3.6.0 now

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
Current GDAL 3.6.0 build 14 test failure
```
 ____________________ test_open_transform_gdal_geotransform _____________________

 path_rgb_byte_tif = '$SRC_DIR/tests/data/RGB.byte.tif'
 
     def test_open_transform_gdal_geotransform(path_rgb_byte_tif):
       """Passing a GDAL geotransform to rasterio.open(transform=...) should raise
         an exception.
        """
     with pytest.raises(TypeError):
             with rasterio.open(
                   path_rgb_byte_tif,
                     transform=tuple(affine.Affine.identity())):
 >               pass
 E               Failed: DID NOT RAISE <class 'TypeError'>

 tests/test_deprecated.py:18: Failed
```

**Comment by weiji14** [comment]
> Current GDAL 3.6.0 build 14 test failure

This test failure should have been fixed in rasterio 1.3.5, see the changelog at https://github.com/rasterio/rasterio/releases/tag/1.3.5, specifically commit https://github.com/rasterio/rasterio/commit/2fb7802b42a1893a7a729f2a6f78deb35229935f which updated the test to use:

```diff
        with rasterio.open(
-                path_rgb_byte_tif,
-                transform=tuple(affine.Affine.identity())):
+            path_rgb_byte_tif, transform=tuple(affine.Affine.identity().to_gdal())
+        ):
            pass
```

Maybe try running on rasterio 1.3.5 (#260) instead of the current main branch (rasterio 1.3.4) and see if it's ok?

**Comment by akrherz** [comment]
Thanks @weiji14 for chiming in!  Build is green now :)

So does @conda-forge/rasterio have thoughts on what we should do here?  Pin down GDAL to 3.6.0?  Upstream is not testing the [maint-1.3 branch](https://github.com/rasterio/rasterio/blob/maint-1.3/.github/workflows/tests.yaml#L40) against GDAL 3.6 it appears :/

**Pull request closed without merging**
