### PR TITLE
Update to 1.1.6; add xylar as maintainer

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This merge also cleans up dependencies (now that py27 is not supported) and updates the list of tests that are failing and will be skipped.

closes #174 
closes #173

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I expect that some of the tests that were failing in previous releases will still be failing but I want to just skip those tests that we really have to.

**Comment by xylar** [comment]
@ocefpaf, I'm not sure what the decision making process was for skipping tests in the past.  Presumably that it's easier to skip them than try to get them fixed upstream?  I'm fine with that, just wanted to see.

**Comment by snowman2** [comment]
> I'm not sure what the decision making process was for skipping tests in the past. 

It is a good idea to raise the issue upstream to check if you are unsure about anything.

**Comment by xylar** [comment]
> It is a good idea to raise the issue upstream to check if you are unsure about anything.

Okay, thanks for the advice.  The test I'm having to disable is `test_boundless_fill_value_overview_masks`.  I'll see if I can put together a minimum build process to reproduce the error and report upstream.  I think pointing upstream to conda-forge CI or even a local conda build isn't likely to be very useful.

**Comment by xylar** [comment]
@conda-forge/rasterio, if you're okay with me removing the matrix of libgdal and disabling the `test_boundless_fill_value_overview_masks` test for now, I think this is ready to merge.  If there are concerns, I'm happy to address them.  I will report the test issue upstream.  I'm not good enough with Windows to try to report those issues upstream, though.  I'll leave them for an expert if someone is interested.

**Comment by xylar** [comment]
I submitted the following issue upstream: https://github.com/mapbox/rasterio/issues/1999

**Pull request merged**
