### PR TITLE
bump build, add test_read_compdcs to skipped tests

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Would like to see what a simple rebuild does

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
OK, same error as #274

> ImportError: libabsl_cord.so.2301.0.0: cannot open shared object file: No such file or directory

**Comment by akrherz** [comment]
@conda-forge-admin please restart ci

**Comment by akrherz** [comment]
Oh dear, now we have a segfault with the new tiledb build in play
```
tests/test_crs.py::test_read_epsg PASSED                                 [  5%]
Fatal Python error: Segmentation fault
```

**Comment by akrherz** [comment]
@conda-forge/rasterio , this PR is now green.  It does add `test_read_compdcs` to the skip list as it is segfaulting, but I have not much idea on how to debug it :(

**Comment by weiji14** [comment]
> @conda-forge/rasterio , this PR is now green. It does add `test_read_compdcs` to the skip list as it is segfaulting, but I have not much idea on how to debug it :(

Looks like the same segfault seen at https://github.com/rasterio/rasterio-wheels/pull/110 and mentioned at https://github.com/rasterio/rasterio-wheels/issues/109#issuecomment-1724693267? Should we wait for upstream `rasterio` to resolve things, or just skip the test for now?

**Comment by sgillies** [comment]
@akrherz I'm not glad about the segfault, but am relieved it's not just me! I wonder WTF is going on. For what it's worth, I'm seeing the same segfault with GDAL 3.6.4 with no change to my build configuration from the one I used to release 1.3.8. I suspect some unspecified piece of my build system has changed in an incompatible way. CMake version? Cython? The CI runner images? I dunno.

**Comment by akrherz** [comment]
Eh, I'm not seeing much strong opinions, so will merge this so to get the proj 9.3 migration done.  Will ensure first we get another green build.

@conda-forge-admin please rerender

**Comment by sgillies** [comment]
@akrherz skipping a crashing test seems risky?

**Comment by akrherz** [comment]
:wave: @sgillies , you are correct, but I don't believe there is bandwidth here to resolve these types of failures that seem transient. Given that it crept in without any rasterio code changes furthers my point.  And lamely, carrying a list of skipped tests for conda-forge packages is more the norm than the exception.  We also have a practical matter of needing to clear migrations so to keep dependency logjams from becoming too severe.  It would also help if conda-forge had more sharp cookies instead of dull/blunt hammers like me :(

**Comment by snowman2** [comment]
> Oh dear, now we have a segfault with the new tiledb build in play
> 
> ```
> tests/test_crs.py::test_read_epsg PASSED                                 [  5%]
> Fatal Python error: Segmentation fault
> ```

This was addressed here: https://github.com/rasterio/rasterio/pull/2875

It is slated for version 1.4.

**Pull request merged**
