### PR TITLE
remove proj4 pin

### PR DESCRIPTION
**Pull request by snowman2**
@conda-forge-admin please rerender.

### CODE REVIEW

**Comment by snowman2** [comment]
@conda-forge-admin please rerender.

**Comment by jorisvandenbossche** [comment]
Will this rerender also fix the fitsio problems? (rasterio import is currently failing, eg https://travis-ci.org/darribas/contextily/jobs/557975681)

**Comment by snowman2** [comment]
Hmmm, looks like #131 may have had something off?

**Comment by ocefpaf** [comment]
> Will this rerender also fix the fitsio problems? (rasterio import is currently failing, eg [travis-ci.org/darribas/contextily/jobs/557975681](https://travis-ci.org/darribas/contextily/jobs/557975681))


@jorisvandenbossche installing `rasterio` should be fixed now but not with latest `proj6`. Still working on that.

**Pull request closed without merging**
