### PR TITLE
Pin gdal 2.1.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Prevents from wrongly downloading `gdal` from the default channel.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@dharhas let me know if you test this release and if it is working.

**Comment by dharhas** [comment]
@ocefpaf Ok I'm having an issue (only tested on OS X so far).

Basically adding ulmo to the requirements is downgrading numpy from 1.11.1 to 1.10.4 and then everything breaks again and its getting gdal/libgdal from the default channel. Without ulmo things seem to be installing correctly.

I'm going to look at ulmo and see what is causing the downgrade.

**Comment by ocefpaf** [comment]
If you have this on a CI log send it to me. I might be able to help by adding missing packages to `conda-forge` and/or updating some pinings. However, if something is explicitly depending on `libgdal`, the only solution is to split `conda-forge`'s `gdal` package.

**Comment by dharhas** [comment]
No this wasn't on CI. I think its probably because ulmo is pinned to pytables <= 3.1.1 because 3.2.0 was segfaulting on windows. I'm guessing that is what is causing numpy to be downgraded.  I can check if the latest pytables fixes the crash and remove the pin.

ulmo doesn't depend on gdal/fiona/rasterio.

**Comment by dharhas** [comment]
@ocefpaf so investigating further. Installing pytables is what is causing libgdal to be install and gdal to be downgraded...

**Comment by kmuehlbauer** [comment]
Seems, it's time for conda-forge `pytables`. There was an attempt here: https://github.com/conda-forge/staged-recipes/pull/312

Also not working: https://github.com/conda-forge/geopandas-feedstock/issues/12

**Comment by ocefpaf** [comment]
> Seems, it's time for conda-forge `pytables`. There was an attempt here: https://github.com/conda-forge/staged-recipes/pull/312

My thoughts exactly :smile: 

I will give it a try tomorrow. (Still in transit... Almost home.)

**Comment by dharhas** [comment]
more info:

Its a hdf5 incompatibility. the gdal recipe specifies hdf5 1.8.17|1.8.17.*

the defaults channel is pinning pytables to hdf5 1.8.16

**Comment by kmuehlbauer** [comment]
IIRC this is to prevent pulling hdf5 1.8.17 from default.

**Comment by dharhas** [comment]
do you mean prevent pulling *1.18.16* from default, defaults doesn't have 1.8.17. pytables is pinned to 1.8.16 in defaults.

**Comment by kmuehlbauer** [comment]
Yes, 1.8.16, I'm on my phone, typo.

**Comment by dharhas** [comment]
@ocefpaf so what is the way forward here? Do we need a conda-forge version pytables or can we drop the hdf5 1.18.17 pin or do we need a conda-forge hdf5 1.18.16?

**Comment by ocefpaf** [comment]
@dharhas the way forward in to get https://github.com/conda-forge/staged-recipes/pull/1133 merged so I can finish https://github.com/conda-forge/staged-recipes/pull/1134

You comment on those PRs is welcomed.

**Pull request merged**
