### PR TITLE
To rasterio 1.0rc3

### PR DESCRIPTION
**Pull request by snowman2**
Addresses issues #63 and #64.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@snowman2 consider adding yourself as a maintainer too. PRs like this one are OK to self-merge.

**Comment by snowman2** [comment]
@ocefpaf is it okay to add myself as a maintainer in this PR?

**Comment by ocefpaf** [comment]
Sure!

**Comment by snowman2** [comment]
Great, I just did. Thanks!

**Comment by ocefpaf** [comment]
Thanks @snowman2!

**Comment by snowman2** [comment]
Glad to help out!

**Pull request merged**
