### PR TITLE
DO NOT MERGE: Remove libgdal matrix, update to gdal 3.1 (take 2)

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Based on this comment from the developer: https://rasterio.groups.io/g/main/message/600, it seems like rasterio 1.1.5 will work with libgdal 3.1 and proj 7.1.0

I wasn't able to re-open #171 because the branch had been deleted so I'm opening a new PR.

**Comment by xylar** [comment]
@akrherz, many tests are failing with GDAL 3.1.2.  If you wan to dig into this and try to figure out why, that would be great.  I don't really have time.

**Comment by akrherz** [comment]
Thank you @xylar ! I am reviewing this all now.

**Comment by akrherz** [comment]
It appears to me the test failures are just with `test_transform_bounds_densify`, which would likely be a proj issue?  I see the tests ran against `7.1.0`, I wonder if it is fixed in `7.1.1` ?  This mapbox/rasterio#1987 PR appears to be passing checks with the GDAL 3.1 and Proj 7.1.1 combination?

**Comment by xylar** [comment]
We could test against proj `7.1.1` but until `conda-forge` updates to its pins to that version, it won't help because no other packages would be built with that version.

**Comment by xylar** [comment]
Yeah, we can't even test with `proj 7.1.1` yet because `libgdal` and possibly other dependencies haven't been built with that version.

**Comment by xylar** [comment]
We would need to do a test build of all of the dependencies that need `proj` first with `proj 7.1.1` and then do a test build of this package with those dependencies.  That's a lot more work than I'm willing to put in just to find out if this package might work later on when `proj` migrates to `7.1.1`.  For now, I think I (once agian) have to conclude that this version of `rasterio` is not compatible with the current pins and this should be closed.

But I'll leave it open until I get your agreement, @akrherz

**Comment by akrherz** [comment]
That's reasonable, you have already gone way above and beyond here.  Thanks again.

**Comment by xylar** [comment]
```
$ conda create -y -n test python=3.8 rasterio conda-tree
$  conda activate test
$ conda tree whoneeds proj
['geotiff', 'libspatialite', 'libgdal']
```
So you would need to do local builds of those three and `rasterio` itself with `proj 7.1.1` if you wanted to see if this will work out.  I can advise on how to do that but it's a lot of work.

**Comment by ocefpaf** [comment]
I started a migration to the new proj 7.1.1. I would love to move to a x.x or even x pinning in proj but their history of breaking things is in micro releases is not encouraging.

**Comment by xylar** [comment]
> I started a migration to the new proj 7.1.1.

Oh, that's great!

> I would love to move to a x.x or even x pinning in proj but their history of breaking things is in micro releases is not encouraging.

Yeah, there's a tricky balance to be had between making things easier for us and breaking things.  In the end, it seems like stricter pins are often worth the pain.  It's such a mess to clean things up if the pin is too loose.

**Pull request closed without merging**
